language: python
dist: trusty
sudo: false
services:
    - docker

before_install:
    - docker build -t journald-2-cloudwatch -f Dockerfile .
install:
    - docker build -t journald-2-cloudwatch-test -f Dockerfile.test .

script:
    - docker run --rm -v "$PWD:$PWD" -w "$PWD"
      -e AWS_DEFAULT_REGION=eu-west-1
      -e AWS_ACCESS_KEY_ID=abc
      -e AWS_SECRET_ACCESS_KEY=abc
      journald-2-cloudwatch-test

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email: false
